server:
  port: 0

spring:
  application:
    name: order-service
  # MySQL ????
  datasource:
    # ???? ???
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  profiles:
    active: db

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true #??? ??? ????
    fetch-registry: true #??? ???? ?? ?? ??? ??
    service-url:
      default-zone: localhost:8761/eureka # ??? ??? ??


